# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SortConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_sort', models.CharField(max_length=255, verbose_name='Agent Sort BY')),
                ('builder_sort', models.CharField(max_length=255, verbose_name='Builder Sort BY')),
                ('property_sort', models.CharField(max_length=255, verbose_name='Property Sort BY')),
            ],
            options={
                'verbose_name': 'Sort Configuration',
            },
        ),
    ]
