# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortconfiguration',
            name='agent_sort',
            field=models.CharField(choices=[('view_count', 'View Count'), ('click_count', 'Click Count'), ('response_count', 'Response Count'), ('proximity', 'Proximity')], default='view_count', max_length=255, verbose_name='Agent Sort BY'),
        ),
        migrations.AlterField(
            model_name='sortconfiguration',
            name='builder_sort',
            field=models.CharField(choices=[('view_count', 'View Count'), ('click_count', 'Click Count'), ('response_count', 'Response Count'), ('proximity', 'Proximity')], default='view_count', max_length=255, verbose_name='Builder Sort BY'),
        ),
        migrations.AlterField(
            model_name='sortconfiguration',
            name='property_sort',
            field=models.CharField(choices=[('view_count', 'View Count'), ('click_count', 'Click Count'), ('response_count', 'Response Count'), ('proximity', 'Proximity')], default='view_count', max_length=255, verbose_name='Property Sort BY'),
        ),
    ]
