# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
        ('agent', '0002_auto_20170530_1836'),
        ('accounts', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.Agent'),
        ),
        migrations.AddField(
            model_name='user',
            name='builder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.Builder'),
        ),
    ]
