# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170704_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=utils.helpers.get_new_avatar_path),
        ),
    ]
