# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170708_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtpVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified at')),
                ('phone', models.CharField(max_length=50)),
                ('pass_code', models.CharField(default='0000', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OtpVerification',
            },
        ),
    ]
