# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0002_auto_20170805_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='categories',
        ),
        migrations.AddField(
            model_name='entry',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='zinnia.Category', verbose_name='category'),
        ),
    ]
