# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 11:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=False),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=False),
        ),
    ]
