# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'verbose_name': 'Blog Image', 'verbose_name_plural': 'Blog Images'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_photo',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='gplus_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google+ URL'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Twitter URL'),
        ),
    ]
