# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:07
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170530_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
