# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170602_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkToExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Talk To Expert',
                'verbose_name': 'Talk To Expert',
            },
        ),
    ]
