# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_talktoexpert'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_views', to='blog.Blog')),
            ],
            options={
                'verbose_name_plural': 'Blog Views',
                'verbose_name': 'Blog View',
            },
        ),
    ]
