# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AlterField(
            model_name='agent',
            name='founded_date',
            field=models.DateField(blank=True, verbose_name='Operating Since'),
        ),
    ]
