# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_auto_20170724_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='logo',
            field=models.ImageField(blank=True, upload_to='agent/'),
        ),
    ]
