# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_auto_20170725_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Payment Expired'),
        ),
        migrations.AddField(
            model_name='agent',
            name='payment_created',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='agent',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='standard',
            field=models.BooleanField(default=False),
        ),
    ]
