# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_propertytype'),
        ('agent', '0010_agent_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='property_type',
            field=models.ManyToManyField(blank=True, null=True, to='property.PropertyType'),
        ),
    ]
