# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourexperts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourexperts',
            name='image',
            field=models.ImageField(help_text='Upload image(.jpg,.png) of size less than 2MB', upload_to='advertisement'),
        ),
    ]
