# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20170803_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified at')),
                ('image', models.ImageField(help_text='Accepted formats are .jpg, .png & .bmp of maximum size 2MB', upload_to='advertisement')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('type', models.CharField(choices=[('normal_banner', 'Normal'), ('property_banner', 'Property')], max_length=25)),
                ('url', models.URLField(blank=True, help_text='If type is Property, provide url here')),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
