# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 09:49
from __future__ import unicode_literals

import applications.advertisement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Accepted formats are .jpg, .png & .bmp of maximum size 2MB', upload_to='banner', validators=[applications.advertisement.models.clean_image]),
        ),
    ]
