# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20170805_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Click Count'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='response_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Response Count'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
