# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_auto_20170810_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBasedPopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('image', models.ImageField(upload_to='activity')),
                ('for_new_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Activity Based Popup',
            },
        ),
        migrations.CreateModel(
            name='UserTimerPopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='timer')),
                ('for_new_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'User Timer Popup',
            },
        ),
    ]
