# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='puja_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='property',
            name='store_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='study_room',
            field=models.BooleanField(default=False),
        ),
    ]
