# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20170601_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_views', to='property.Property')),
            ],
            options={
                'verbose_name': 'Property View',
                'verbose_name_plural': 'Property Views',
            },
        ),
    ]
