# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_propertyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('buyer_owner', 'Buyer/Owner'), ('agent', 'Agent'), ('builder', 'Builder')], default='buyer_owner', max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('message', models.TextField(blank=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_property_responses', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_responses', to='property.Property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_property_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Property Responses',
                'verbose_name': 'Property Response',
            },
        ),
    ]
