# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_propertyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='builder',
        ),
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='property.FacilityType'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.TextField(null=True, verbose_name='Property Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('residential_apartment', 'Residential Apartment'), ('residential_villa', 'Residential Villa'), ('commercial_showroom', 'Commercial Showroom'), ('commercial_shop', 'Commercial Shop')], max_length=100),
        ),
    ]
