# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20170609_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furnished_status',
            field=models.CharField(blank=True, choices=[('non_furnished', 'Non-Furnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished')], max_length=100),
        ),
    ]
