# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20170612_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyview',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='propertyview',
            name='datestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
