# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20170626_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='loc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Locality'),
        ),
    ]
