# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_property_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='cit',
            new_name='city',
        ),
    ]
