# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20170626_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='loc',
            new_name='locality',
        ),
    ]
