# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 01:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20170626_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='locality',
        ),
        migrations.AlterField(
            model_name='property',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
