# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_locality_coordinates'),
        ('property', '0017_auto_20170707_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
        ),
        migrations.AddField(
            model_name='property',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Locality'),
        ),
    ]
