# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20170707_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='completeness_percent',
        ),
    ]
