# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20170707_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=utils.helpers.get_new_property_image_path),
        ),
    ]
