# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_propertyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
