# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20170725_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_payment_expired',
            field=models.BooleanField(default=False, verbose_name='Payment Expired'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_created_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
    ]
