# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20170727_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Hit Count'),
        ),
        migrations.AddField(
            model_name='property',
            name='response_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Response Count'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
