# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_property_click_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Property Types',
                'verbose_name': 'Property Type',
            },
        ),
    ]
