# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_propertytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified at')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Click Count')),
                ('response_count', models.PositiveIntegerField(default=0, verbose_name='Response Count')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_analytics', to='property.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
