# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_auto_20170810_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyanalytics',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=0, verbose_name='Month'),
        ),
    ]
