# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builder',
            options={},
        ),
        migrations.AddField(
            model_name='builder',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
        ),
    ]
