# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20170530_1836'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='property_types',
            field=models.ManyToManyField(blank=True, related_name='property_types', to='property.Property'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
