# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('builder', '0003_auto_20170530_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builder',
            name='location',
        ),
        migrations.AddField(
            model_name='builder',
            name='cities',
            field=models.ManyToManyField(blank=True, to='locations.City'),
        ),
        migrations.AddField(
            model_name='builder',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
