# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 07:01
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20170601_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builder',
            name='property_types',
        ),
        migrations.AddField(
            model_name='builder',
            name='property_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('residential_apartment', 'Residential Apartment'), ('residential_villa', 'Residential Villa'), ('commercial_showroom', 'Commercial Showroom'), ('commercial_shop', 'Commercial Shop')], default=False, max_length=100),
        ),
    ]
