# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_auto_20170724_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Payment Expired'),
        ),
        migrations.AddField(
            model_name='builder',
            name='payment_created',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='builder',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='builder',
            name='standard',
            field=models.BooleanField(default=False),
        ),
    ]
