# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingProperty',
            fields=[
                ('property_id', models.IntegerField(db_column='MarketingPropertyId', primary_key=True, serialize=False)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_type', models.CharField(blank=True, max_length=25, null=True)),
                ('property_carpet_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('construction_age', models.CharField(blank=True, max_length=100)),
                ('locality', models.CharField(max_length=255, null=True)),
                ('full_address', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('property_total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('property_units', models.CharField(blank=True, max_length=50)),
                ('bedroom', models.PositiveIntegerField(blank=True, null=True)),
                ('bathroom', models.PositiveIntegerField(blank=True, null=True)),
                ('pooja_room', models.PositiveIntegerField(blank=True, null=True)),
                ('study_room', models.PositiveIntegerField(blank=True, null=True)),
                ('balcony', models.PositiveIntegerField(blank=True, null=True)),
                ('flooring', models.PositiveIntegerField(blank=True, null=True)),
                ('furnishing', models.CharField(blank=True, max_length=100)),
                ('pantry', models.CharField(blank=True, max_length=50)),
                ('maintenance_charge', models.PositiveIntegerField(blank=True, null=True)),
                ('landmarks', models.TextField(blank=True)),
                ('car_park', models.PositiveIntegerField(blank=True, null=True, verbose_name='Four Wheeler Parking count')),
                ('project_details', models.TextField(blank=True)),
                ('width_road_facing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_of_open_sides', models.PositiveIntegerField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'MarketingProperty',
            },
        ),
    ]
