# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingproperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingproperty',
            name='balcony',
            field=models.PositiveIntegerField(blank=True, db_column='balcony', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='bathroom',
            field=models.PositiveIntegerField(blank=True, db_column='bathroom', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='bedroom',
            field=models.PositiveIntegerField(blank=True, db_column='bedroom', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='car_park',
            field=models.PositiveIntegerField(blank=True, db_column='car_park', null=True, verbose_name='Four Wheeler Parking count'),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='construction_age',
            field=models.CharField(blank=True, db_column='construction_age', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='floor',
            field=models.PositiveIntegerField(blank=True, db_column='floor', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='flooring',
            field=models.PositiveIntegerField(blank=True, db_column='flooring', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='full_address',
            field=models.CharField(db_column='full_address', max_length=200),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='furnishing',
            field=models.CharField(blank=True, db_column='furnishing', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='landmarks',
            field=models.TextField(blank=True, db_column='landmarks'),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='length',
            field=models.DecimalField(blank=True, db_column='length', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='locality',
            field=models.CharField(db_column='locality', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='maintenance_charge',
            field=models.PositiveIntegerField(blank=True, db_column='maintenance_charge', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='no_of_open_sides',
            field=models.PositiveIntegerField(blank=True, db_column='no_of_open_sides', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='pantry',
            field=models.CharField(blank=True, db_column='pantry', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='pooja_room',
            field=models.PositiveIntegerField(blank=True, db_column='pooja_room', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='project_details',
            field=models.TextField(blank=True, db_column='project_details'),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='project_name',
            field=models.CharField(db_column='project_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='property_carpet_area',
            field=models.DecimalField(blank=True, db_column='property_carpet_area', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='property_total_floors',
            field=models.PositiveIntegerField(blank=True, db_column='property_total_floors', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='property_type',
            field=models.CharField(blank=True, db_column='property_type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='property_units',
            field=models.CharField(blank=True, db_column='property_units', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='seller_type',
            field=models.CharField(blank=True, db_column='seller_type', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='study_room',
            field=models.PositiveIntegerField(blank=True, db_column='study_room', null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='total_price',
            field=models.DecimalField(blank=True, db_column='total_price', decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='transaction_type',
            field=models.CharField(blank=True, db_column='transaction_type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketingproperty',
            name='width_road_facing',
            field=models.DecimalField(blank=True, db_column='width_road_facing', decimal_places=2, max_digits=10, null=True),
        ),
    ]
