# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketingproperty', '0004_auto_20170628_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertydetails',
            options={},
        ),
    ]
