# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketingproperty', '0006_auto_20170628_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertydetails',
            options={'managed': False, 'verbose_name': 'Property Details', 'verbose_name_plural': 'Property Details'},
        ),
    ]
