# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogStashConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elastic_host', models.URLField(max_length=255)),
                ('last_procesed', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Logstash Configuration',
            },
        ),
    ]
