# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logstashconfiguration',
            options={'verbose_name': 'LogStash Configuration'},
        ),
        migrations.AlterField(
            model_name='logstashconfiguration',
            name='last_procesed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
