# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20170731_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstashconfiguration',
            name='index',
            field=models.CharField(default='nginx-api-access', max_length=255),
        ),
    ]
