# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_logstashconfiguration_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logstashconfiguration',
            name='elastic_host',
            field=models.URLField(default='https://search-wynvent-staging-x24kbpqvt4mmhexwbbb3hhqn6q.us-west-2.es.amazonaws.com/', max_length=255),
        ),
    ]
